### ISSUE TITLE
OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by zhuhuixiang** [mmendiet/FedAlign#1]
When I run the main.py with the recommended arguments `python main.py --method fedalign --client_number 16 --thread_number 16 --comm_round 25 --lr 0.01 --epochs 20 --width 0.25 --mu 0.45 --data_dir data/cifar100`, I got the following error. It happened after finishing the first local iterations of client0. 
 `INFO:root:************** Round: 0 ***************
INFO:root:(client 0. Local Training Epoch: 0 	Loss: 1.819505  Thread 1  Map [0]
INFO:root:(client 0. Local Training Epoch: 1 	Loss: 1.794823  Thread 1  Map [0]
INFO:root:(client 0. Local Training Epoch: 2 	Loss: 1.775222  Thread 1  Map [0]
INFO:root:(client 0. Local Training Epoch: 3 	Loss: 1.754200  Thread 1  Map [0]
INFO:root:(client 0. Local Training Epoch: 4 	Loss: 1.732598  Thread 1  Map [0]
INFO:root:(client 0. Local Training Epoch: 5 	Loss: 1.710265  Thread 1  Map [0]
INFO:root:(client 0. Local Training Epoch: 6 	Loss: 1.688822  Thread 1  Map [0]
INFO:root:(client 0. Local Training Epoch: 7 	Loss: 1.668204  Thread 1  Map [0]
INFO:root:(client 0. Local Training Epoch: 8 	Loss: 1.649973  Thread 1  Map [0]
INFO:root:(client 0. Local Training Epoch: 9 	Loss: 1.634276  Thread 1  Map [0]
INFO:root:(client 0. Local Training Epoch: 10 	Loss: 1.618046  Thread 1  Map [0]
INFO:root:(client 0. Local Training Epoch: 11 	Loss: 1.605212  Thread 1  Map [0]
INFO:root:(client 0. Local Training Epoch: 12 	Loss: 1.592514  Thread 1  Map [0]
INFO:root:(client 0. Local Training Epoch: 13 	Loss: 1.579208  Thread 1  Map [0]
INFO:root:(client 0. Local Training Epoch: 14 	Loss: 1.568651  Thread 1  Map [0]
INFO:root:(client 0. Local Training Epoch: 15 	Loss: 1.559061  Thread 1  Map [0]
INFO:root:(client 0. Local Training Epoch: 16 	Loss: 1.548159  Thread 1  Map [0]
INFO:root:(client 0. Local Training Epoch: 17 	Loss: 1.538477  Thread 1  Map [0]
INFO:root:(client 0. Local Training Epoch: 18 	Loss: 1.529025  Thread 1  Map [0]
INFO:root:(client 0. Local Training Epoch: 19 	Loss: 1.520388  Thread 1  Map [0]
INFO:root:************* Client 0 Acc = 31.51 **************
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/server1/.pycharm_helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/server1/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/media/server1/ef9c36bf-023a-4a24-9852-c85fbc39a794/zhuhuixiang/python_Project/FedAlign-main/main.py", line 234, in <module>
    client_outputs = pool.map(run_clients, server_outputs)
  File "/home/server1/anaconda3/envs/zhuhuixiang/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/server1/anaconda3/envs/zhuhuixiang/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/home/server1/anaconda3/envs/zhuhuixiang/lib/python3.7/multiprocessing/pool.py", line 431, in _handle_tasks
    put(task)
  File "/home/server1/anaconda3/envs/zhuhuixiang/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/server1/anaconda3/envs/zhuhuixiang/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/server1/anaconda3/envs/zhuhuixiang/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 327, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/server1/anaconda3/envs/zhuhuixiang/lib/python3.7/multiprocessing/reduction.py", line 194, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/server1/anaconda3/envs/zhuhuixiang/lib/python3.7/multiprocessing/resource_sharer.py", line 48, in __init__
    new_fd = os.dup(fd)
OSError: [Errno 24] Too many open files`.
It seems that something is wrong when calling the 'pool.map' function to enable multi-threaded acceleration. Moreover, the version of torch used is 1.2.0 due to the limit of the old CUDA version. Thanks!

**Comment by zhuhuixiang** [comment]
I have solved it by adding "torch.multiprocessing.set_sharing_strategy('file_system')" to the main.py. Using the `file_system` strategy, the CUDA tensor is transferred directly between processes to avoid excessive file descriptor generation.
