### ISSUE TITLE
problem for multi-process codes

### ISSUE THREAD

**Issue by chrisyxue** [mmendiet/FedAlign#3]
Hello, very impressive work! 

Just have a problem about the multi-process codes, could you please tell me how to solve it?

Traceback (most recent call last):
  File "main.py", line 224, in <module>
    pool = cm.MyPool(args.thread_number, init_process, (client_info, Client))
  File "/localscratch/xuezhiyu/anaconda3/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/localscratch/xuezhiyu/anaconda3/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/localscratch/xuezhiyu/anaconda3/lib/python3.8/multiprocessing/pool.py", line 319, in _repopulate_pool_static
    w = Process(ctx, target=worker,
  File "/localscratch/xuezhiyu/anaconda3/lib/python3.8/multiprocessing/process.py", line 82, in __init__
    assert group is None, 'group argument must be None for now'
AssertionError: group argument must be None for now

**Comment by henry-tujia** [comment]
I'm afraid that this code is only fine for python<=3.7. But still want to see the problem to be sovled.

**Comment by henry-tujia** [comment]
I guess you can check this out [Here](https://github.com/LoLab-VU/PyDREAM/pull/17)
